### PR TITLE
resized photo, updated _data/sidebar_doc.yml

### PR DESCRIPTION
**Pull request by turbomam**

### CODE REVIEW

**Review by nlharris — CHANGES_REQUESTED** [review]
Oops, I also changed sidebar_doc.yml, so can you withdraw that part of your PR? (I'm actually not sure exactly how to do that--it'll be a learning opportunity for both of us!)

**Comment by turbomam** [comment]
re withdrawing the `sidebar_doc.yml` part of the PR. Sure, I'll do whatever you want.

Could we try resolving the conflict? If you have merged your edit into the base/master/main, I can merge that into my branch and see what the conflicts are.

Or I can withdraw the PR and start over.

**Comment by nlharris** [comment]
i can merge and then see if any conflicts remain

**Comment by nlharris** [comment]
all good! merge was successful.

**Pull request merged**
