### PR TITLE
Automatically resize logos

### LINKED ISSUE #68: automatically resize logos
Project logos show up full-size, which can be way too big. Should constrain logos to be a max size.
(I thought there was an already issue about this but I don't see it.)

Screen Shot 2022-10-23 at 12 08 44 PM

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #68 

@nlharris I don't think it's really appropriate for me to be making a contribution like this since I don't belong to this organization, but since I did want to make sure that SSSOM messaging was up-to-date since it's a reflection of my work, which sort of led to the issue, I guess it's alright

### CODE REVIEW

**Comment by nlharris** [comment]
It's totally appropriate -- BBOP is an open organization and we welcome contributions from community volunteers like you! Your addition of the SSSOM logo reminded me of an issue that we have with our website, and I'm delighted that you are offering a fix for it! Thank you! 🙌

**Comment by nlharris** [comment]
It works! 👍
And next time an issue like this arises, I will know what to do to fix it!

**Comment by cthoyt** [comment]
I think you misunderstood. For sure it's fine for an organization to accept high skilled free labor. I mean it is not personally good for me to give away this stuff for free in situations like this. But I realized explaining that in a nice way would take longer than just sending the fix...

**Comment by nlharris** [comment]
You generously contribute your expertise and time to other open organizations; I don't see why helping our group (which openly shares its resources) is any worse.

Regardless, I realize you have finite time and energy, and I am grateful that you devoted some of it to help us!

**Comment by cthoyt** [comment]
Yes, I'm worried about either burning out or just getting so frustrated I have to take a big step back

**Comment by nlharris** [comment]
I get it. I too am involved in many unpaid efforts, and sometimes have to restrain my natural urge to be helpful.

**Pull request merged**
